<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        /*
        
        1、错误的类型
        Error：所有错误的父类型
        ReferenceError：引用的变量不存在
        TypeError：数据类型不正确的错误
        RangeError：数据值不在其允许范围内
        SyntaxError：语法错误

        2、错误处理
        捕获错误：try ... catch
        抛出错误：throw error

        3、错误对象
        message属性：错误相关信息
        stack属性：函数调用栈记录信息

        */

        // 常见的内置错误
        // 01、ReferenceError：引用的变量不存在
        // console.log(a)  //ReferenceError: a is not defined

        // 02、TypeError：数据类型不正确的错误
        // let b = null
        // console.log(b.xxx) //TypeError: Cannot read properties of null (reading 'xxx')

        // 03、RangeError：数据值不在其允许范围内
        // function fn(){
        //     fn()
        // }
        // fn()   //RangeError: Maximum call stack size exceeded

        // 04、SyntaxError：语法错误
        // const c = """"  //SyntaxError: Unexpected string



        // 2、错误处理
        // 捕获错误：try ... catch
        // try {
        //     let d;
        //     console.log(d.xxx);
        // } catch (error) {
        //     console.log(error.message);
        //     console.log(error.stack);
        // }
        // console.log('出错之后');

        // 抛出错误：throw error
        function something() {
            if (Date.now() % 2 === 1) {
                console.log('当前时间为奇数，可以执行。');
            } else {
                // 抛出异常，用调用者来处理
                throw new Error('当前时间为偶数，无法执行任务。')
            }
        }

        // 捕获异常
        try {
            something()
        } catch (error) {
            alert(error.message)
        }
        something()
    </script>
</body>

</html>